name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Update README
        run: |
          cp README.md README_en.md
          cp README_es.md README.md
          git add README.md
          git commit -m "Update README"
          git push
